### ISSUE TITLE
Theme formatting for annotation references in text

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#119]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to make my annotation references superscript. Others might want other formatting on these references too.

**Describe the solution you'd like**
A `Theme` formatting section for references OR an option to specifically superscript annotation references

This is going to require splitting strings into rich-text lists and inserting a `{superscript: True}` element before the reference text.

**Comment by rowanhemsi** [comment]
As stated in [Analysis Function guidance published 2021-06-30](https://analysisfunction.civilservice.gov.uk/policy-store/releasing-statistics-in-spreadsheets/), superscript text does not meet the accessibility guidelines and this option will not be added to gptables
