### ISSUE TITLE
Change GPTable legend to dict

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#129]
**Describe the solution you'd like**
It would make sense to make the legend a dict of `{marker: explanation}` to ensure that structure is consistent. Especially given that we automatically generate a legend for missing values.

Note: would not be backwards compatible, though I haven't seen much use of the manual legend.

**Comment by rowanhemsi** [comment]
Note: as of v1.0.0, missing value behaviour has changed and legend is no longer automatically generated
