### ISSUE TITLE
Support rich text list with length of 2

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#134]
**Is your feature request related to a problem? Please describe.**
E.g. I'd like to format a hyperlink, but don't have more than one piece of text to put into the rich text list.

**Describe the solution you'd like**
I'd like to provide a list with 1 format dict and 1 string. This format should be added to the cells formatting and then the single string written as normal.

**Comment by rowanhemsi** [comment]
Note: hyperlinks are now formatted as underlined blue text. However, this could still be of use for the custom formatting of specific elements of text, eg. currently same formatting is applied to all subtitles. User may prefer for different subtitles to have different formatting

**Comment by rowanhemsi** [comment]
Functionality added in #210
