### ISSUE TITLE
Hyperlinks are not formatted automatically (blue and underlined)

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#135]
**Describe the bug**
Creating a hyperlink using a formula (`=HYPERLINK()`) results in a plain-formatted link. I think the Theme formatting is overriding the Excel hyperlink format.

**Expected behavior**
Hyperlinks should be blue and underlined by default (or via option).

**Additional context**
Hyperlink formatting could be a Theme option, along with footnote references?

**Comment by rowanhemsi** [comment]
Hyperlinks can now be added to text using the formatting `[display text](link)`. The display text will then be written in blue and underlined, linking to the provided location. 

Note: as with all Excel files, the whole cell containing a link will have the link and formatting, not just the display text provided

For any further problems or requirements regarding formatting of links, please open a new issue
