### ISSUE TITLE
Improve table accesibility

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#143]
- [ ] Write as .ods
- [x] Markup table as a table, with headers also marked up
- [x] Move units into headers cell, surrounding them with parentheses
- [x] Move notes to single notes page
       Notes would need to be passed to the `write_/produce_workbook` methods in this case. Or we could refactor Cover to be a generic Workbook kinda object to hold tables, coversheets and notes.

**Comment by alexander-newton** [comment]
We need to do our own consultation with users.

**Comment by foster999** [comment]
Would be good to know what would be most useful for them. However, they always have the option to not upgrade to the next major version, so we shouldn't not adopt good practices just because it changes the API. I think this will be a reasonably large API change either way

**Comment by foster999** [comment]
- [ ] Use square brackets around note markers
- [ ] Or create a notes column at far right?
