### ISSUE TITLE
Automatic colour written incorrectly to file?

### ISSUE THREAD

**Issue by jtrim-ons** [best-practice-and-impact/gptables#157]
**Describe the bug**
Within the zipped .xlsx file, Excel normally writes the "Automatic" colour by omitting the `<color>` tag within a `<font>` tag. The dev version of gptables writes `<color rgb="FFAUTOMATIC"/>` within the font tag. My guess is that this happens because XlsxWriter doesn't recognise the automatic colour.

When you open the created file in Excel it works fine, but LibreOffice shows the "FFAUTOMATIC" colour as `#000FFA`. 

**To Reproduce**
On Mac:
Run `examples/iris_cover.py`
Copy the .xlsx file to a new directory and `cd` to that directory.
`unzip python_iris_cover_gptable.xlsx`
`# Pretty print and show the first 20 lines:`
`cat xl/styles.xml | xmllint --format - | head -n20`

**Expected behavior**
"Automatic" coloured fonts should have no `<color>` tag in `xl/styles.xml`

**Screenshots**
In LibreOffice:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/79704945/151879715-a69521dd-3cfc-4e1f-9ca7-73a41bc9dfab.png">

**Additional context**
I'm not sure if there's a way around this with the current XlsxWriter.

**Comment by jtrim-ons** [comment]
Amazing. Thanks @rowanhemsi and @jmcnamara!

**Comment by rowanhemsi** [comment]
Requirements updated on dev branch, to be deployed in v1.2.0
