### ISSUE TITLE
Rich text in cover sheet

### ISSUE THREAD

**Issue by ldavies99** [best-practice-and-impact/gptables#205]
**Is your feature request related to a problem? Please describe.**
We want to be able to highlight some text in the about section in bold but cannot.

**Describe the solution you'd like**
We'd like to able to format rich text in the cover page the same way you can in the data sheets.

**Additional context**
This became apparent when trying to replicate the example spreadsheet from "Releasing Statistics in Spreadsheets" using gptables.

**Comment by rowanhemsi** [comment]
Fixed in #210
