### ISSUE TITLE
Additional formatting in cover page

### ISSUE THREAD

**Issue by ldavies99** [best-practice-and-impact/gptables#214]
**Is your feature request related to a problem? Please describe.**
I want to be able to change the cell heights in the cover page and wrap the text in them.

**Describe the solution you'd like**
Allow for additional formatting in the cover page and add the functionality described above if it does not exist already.

**Additional context**
Trying to replicate the example sheet from [here](https://analysisfunction.civilservice.gov.uk/policy-store/releasing-statistics-in-spreadsheets/#section-17) using gptables.

**Comment by rowanhemsi** [comment]
Text wrapping added in #215
Height customisation can be done using xlsxwriter and will not be added to gptables at this time
