### ISSUE TITLE
XlsxWriter autofit() method

### ISSUE THREAD

**Issue by rowanhemsi** [best-practice-and-impact/gptables#217]
Investigate [new XlsxWriter `autofit()` function](https://xlsxwriter.readthedocs.io/worksheet.html#worksheet.autofit) as possible enhancement/replacement for `auto_width` functionality

**Comment by ldavies99** [comment]
After testing I have found that it is not a viable replacement for the current auto_width functionality for two reasons:

- As stated in the xlsxwriter documentation; "It is based on the default font and font size of Calibri 11. It will not give accurate results for other fonts or font sizes."
- There is no option to ignore the the title and subtitle rows in the table sheets which makes the first column far too wide in most cases.
