### ISSUE TITLE
Add Worksheet method for adding a GPTable

### ISSUE THREAD

**Issue by alexander-newton** [best-practice-and-impact/gptables#23]
~~- [ ] `GPTable` is a subclass of `Worksheet`~~
- [x] `write_gptable` method of worksheet wrapper. This takes a GPTable and uses the Workbook's Theme.

**Comment by foster999** [comment]
Considering this, I think it might make more sense to treat the GPTable as a separate object to a worksheet. A write_gptable method could work similar to the existing write_table method, but with additional features.

**Comment by jazzbuck** [comment]
sounds good - might be that we can mask `write_table` for `GPTable`a rather than make a new method? Just thinking about vocabulary for the users.

**Comment by alexander-newton** [comment]
- [ ] add additional formatting functionality by row, column, and cell in that order of priority
