### ISSUE TITLE
Correct licence to BSD

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#29]
License should be in line with [XlsxWriter](https://github.com/jmcnamara/XlsxWriter)

**Comment by alexander-newton** [comment]
For the record, licenses are compatible:
https://opensource.stackexchange.com/questions/217/what-are-the-essential-differences-between-the-bsd-and-mit-licences

BSD makes implicit allowances. We must reproduce BSD as we are using XlsxWriter.
