### ISSUE TITLE
Assess whether we're duplicating effort

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#30]
Similar package exists: [XlsxPandasFormatter](https://github.com/webermarcolivier/xlsxpandasformatter)

**Comment by alexander-newton** [comment]
Hah, we should have known we'd find something eventually. It looks really useful / good - think that we could pretty much use this and have a convenience function for themes. What do you reckon?

**Comment by alexander-newton** [comment]
How did you find this?

**Comment by alexander-newton** [comment]
Let's talk about this tomorrow

**Comment by foster999** [comment]
Need to look into it a bit more, but does look useful! Embarrassingly found it [here](https://xlsxwriter.readthedocs.io/third_party.html)...

**Comment by alexander-newton** [comment]
For the record:

- we decided that we can definitely use some of the ideas in these other packages
- the main advantage of our package is its strong opinionation which the other packages lack
- the other packages lack important features like testing and documentation
- we should continue to write our package
