### ISSUE TITLE
default_styles.yaml (currently gptable.yaml in root on dev)

### ISSUE THREAD

**Issue by alexander-newton** [best-practice-and-impact/gptables#34]
I'm not really sure where we should put this - putting it in the root directory seems silly but it isn't strictly an `example` - I think we should put it in the example dir and then include a `pickle` of the `gptheme` to include in `core`?

**Comment by foster999** [comment]
Agreed, that seems best to me. We should add a comment to the final example .yaml, to clarify that it's used to create the default Theme

**Comment by foster999** [comment]
Duplicae of #46
