### ISSUE TITLE
Additional outputs as .csv

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#39]
Each output should also be produced as a machine readable .csv file by default, to encourage publication of both formats

**Comment by foster999** [comment]
@alexander-newton should .csv versions contain all elements, or only data table?

**Comment by alexander-newton** [comment]
just data table

**Comment by alexander-newton** [comment]
this is probably something further up the pipeline rather than in `gptables`

**Comment by foster999** [comment]
It would be good to encourage people to do it though, and would be easy enough to build into the API function

**Comment by alexander-newton** [comment]
Agreed that we need to encourage people to do it. I think that it's feature creep for `gptables` and would be really hard to do well as summaries will be difficult to implement.

**Comment by alexander-newton** [comment]
Perhaps we could include a message that says "Are you going to publish a csv of your data?"
