### ISSUE TITLE
GPWorksheet _write_table_elements is not correct

### ISSUE THREAD

**Issue by jazzbuck** [best-practice-and-impact/gptables#49]
**Describe the bug**

This behaviour is on the `dev` branch.

- [x] Some interesting behaviour with the pandas dataframes is caused by not considering the difference between copies and pointers. When we take data into the _write_table_elements method we should make sure we're bringing in copies to not mess up any dataframes in the nonlocal environment.
- [x] These are exacerbated by some harder design choices. For example, `data.iloc[-1] = data.columns` on line 183 in `wrappers.py` isn't doing what it is intended to do. It is currently overwriting the bottom row with the column names.
- [ ] I really like the simplicity of this implementation. However, I think we might want to make `just_one_more` abstraction. Appreciate this sounds silly but I think that we should have an object, perhaps in `Theme` that specifies the positioning of the various elements. It's something we talked about before and we agreed that we wanted a strong steer on what `good_practice` means. However, I think that having some configuration ability on the positioning of elements will be really helpful in the future - especially as we receive requests for more table elements. Let me know your thoughts.
- [x] `subtitles` isn't working for some bizarre reason. I'm going to have another look but I have not been able to figure it out as-of-yet. If I apply `iris_table.subtitles = [subtitle]` directly then it seems to work, and `iris_table.set_subtitles = [subtitle]` also works, but GPTable(**kwargs) with the correct arguments doesn't seem to work. I think it might be to do with the defaults.

**To Reproduce**

If you run iris.py in REPL you can find some interesting things. For instance, before line 82 in `iris.py` then `iris_summ` is as expected. However, after that block `iris_summ` gets all messed up. There's also a minor bug in your kwargs which is setting `index = {1:1,2:2}` when it should be `index = {1:0, 2:1}` - I will push to correct.

**Comment by foster999** [comment]
Final comment moved to feature request #51
