### ISSUE TITLE
Flexible element positioning

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#51]
**Is your feature request related to a problem? Please describe.**
It would be useful if users had more control over the relative positioning of some GPTable elements, within our guidance.

**Describe the solution you'd like**
Theme (or an object within a Theme) should take positional arguments for elements.

Some examples:

- [x] Order of legend, annotations, notes and source

- [ ] Units positioned above or below header

- ~~[ ] Control over spacing between elements?~~ Spacing not allowed

**Comment by foster999** [comment]
@alexander-newton 
Any thoughts on 2 and 3 above?
2. Should units position be flexible, and would above and below be suitable?
3. Should we allow variable spacing between elements? And which elements

Should the position of any other elements be variable? I think it's best to keep most along the leftmost side, with minimal gaps between them, for computer readability

**Comment by alexander-newton** [comment]
2. yes.
3. I'm no longer sure. I think you're right that this doesn't follow good practice.

**Comment by foster999** [comment]
Leaving this open, but I don't think we'll support units below headings unless requested

**Comment by rowanhemsi** [comment]
Units moved to below headers, on a new line within the same row. This is in line with the [Analysis Function guidance published 2021-06-30](https://analysisfunction.civilservice.gov.uk/policy-store/releasing-statistics-in-spreadsheets/)
