### ISSUE TITLE
Missingness, zeroes, NAs, and legend

### ISSUE THREAD

**Issue by alexander-newton** [best-practice-and-impact/gptables#53]
**Is your feature request related to a problem? Please describe.**

Need implementation for zeroes, missings, n/a's and other data points. This will be a frequent request and it doesn't make sense for users to have to convert their dataframes to text columns to input `.`, `..`, or `-` every time they have different types of missingness.

**Describe the solution you'd like**

I'd like a function in write_worksheet that looks at `GPTable.legend`, interprets the different types of missingness in the data, and writes out the correct symbol. There will be defaults where `.legend` doesn't express an opinion.

**Describe alternatives you've considered**

We could also have a utility function for this as they input the data to GPTable. I think this isn't as clean a solution.

**Comment by foster999** [comment]
@alexander-newton I'm not sure how feasible this is. How would these types be represented in the input (pandas DataFrame)?
I can only envisage use of `numpy.nan` and perhaps `None` (object type only).

We could certainly have an default missing attribute in `gptables.Theme`, for converting `nan`?

**Comment by alexander-newton** [comment]
Yeah I think that `.nan` would be a good start. I think our guidance is that `..` represents `NA`, `.` represents rounded to zero, and `-` means zero.

**Comment by foster999** [comment]
[Symbol guidance](https://gss.civilservice.gov.uk/wp-content/uploads/2017/03/GSS-Website-Harmonised-Symbols-Supporting-Documentation.pdf) suggests:

- `0` is fine if truly 0

- `z` if not applicable

- `:` if not available

- `~` if number has been rounded to 0. This should go in a separate col

**Comment by alexander-newton** [comment]
^ sounds good.

**Comment by foster999** [comment]
`np.nan`s handled in #61 

Should change legend to dict and check if key is used in table, so that only used keys are shown

Could also look into handling rounded to 0 elements (`~`). Find default rounding level, for when user does not specify

**Comment by rowanhemsi** [comment]
[Analysis Function guidance published 2022-01-11](https://analysisfunction.civilservice.gov.uk/policy-store/symbols-in-tables-definitions-and-help/) details latest guidance on the use of symbols and shorthand. Following conversation with users, v1.0.0 allows empty cells within data tables, with the understanding that this should only be done if there is only one (explained) reason for missingness. If there is more than one reason for missingness, users are asked to add suitable shorthand to their data. This shorthand should be explained in the legend or instructions property. For any problems or requests following this release, please create a new issue
