### ISSUE TITLE
Support for various notes

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#54]
Should we support notes that are not referenced anywhere in other GPTable elements?

Should we support references within the data cells of the table? This will corrupt data, by rounding to the desired decimal place and changing the type.

**Comment by jazzbuck** [comment]
1. Yes - I guess we just wouldn't assign a number? e.g.
> This is a quote without a reference.
> 1. This is a quote with a reference.

2. I don't think we should do this.

**Comment by foster999** [comment]
Sounds sensible.

I'll likely split notes into "annotations" and "notes", so that the user is explicit if they intend to reference it (A warning is currently printed if a note is not referenced).

Let me know if you have any other suggestions for naming notes with (annotations?) and without references

**Comment by foster999** [comment]
Implemented in #55
