### ISSUE TITLE
Automatically set column widths

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#56]
**Is your feature request related to a problem? Please describe.**
Long index names are currently hidden, as they overlap the next column. This could also occur for scope and units. All other non-table elements are a single element per line, so shouldn't have this issue

**Describe the solution you'd like**
Column widths to be set automatically, depending on the text in:

- index columns

- column headings

This would need to take into account:

- font size

- font formatting

- text alignment and wrapping

**Comment by alexander-newton** [comment]
And row heights?

**Comment by foster999** [comment]
Row heights would be difficult to automate, so will leave this down to the user for now (`worksheet.set_row(row_number, height)`)

**Comment by foster999** [comment]
To account for wrapped text, we could take a set width for these cols in the Theme. Consider if we should support this for only column headings and indexes? As wrapping other Column A elements is not possible without merging cells (which is against good practice guidance)

**Comment by foster999** [comment]
#108 follows this up
