### ISSUE TITLE
Units dictionaries 

### ISSUE THREAD

**Issue by ramizfarishta** [best-practice-and-impact/gptables#69]
**Describe the bug**
Dictionaries don't work for units

**To Reproduce**
When passing in a dictionary to map units to column titles, there is no output
units = {"title1":"unit1", "title2":"unit2", "title4":"unit4"}

**Expected behavior**
Expect respective unit to be mapped to column title when written out in the dictionary. If title-unit key-value not mentioned, should not map a unit to column

**Comment by alexander-newton** [comment]
Options for mapping by int index or str

**Comment by foster999** [comment]
Fixed in #73
