### ISSUE TITLE
Quick mode

### ISSUE THREAD

**Issue by alexander-newton** [best-practice-and-impact/gptables#80]
**Is your feature request related to a problem? Please describe.**
Not all of my outputs are official statistics and don't need the same rigour of communication. I want a way to quickly output in nice looking tables without having to worry about providing information like `source`, `title`, `subtitle`, `scope`, `table`. 

**Describe the solution you'd like**
I would like an `quick_and_dirty` option for producing tables that are clearly not best practice but are still good looking. I want this to automatically pick up key bits of information (e.g. table, index columns, and headings) without me having to be so explicit. It should be a single required argument function that takes a single, or list of, data frames.

**Comment by foster999** [comment]
#106
