### ISSUE TITLE
gptheme default can be modified, leading to non-explicit use of the modified theme

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/gptables#93]
**Describe the bug**
If a user imports gptheme and modifies the object, calls to write/produce_workbook() API functions will use the modified theme by default

**Expected behavior**
The API functions should create a new Theme instance from the default config (gptheme.yaml) when no theme is passed. A user should explicitly pass the modified theme to the API functions to use it.

**Comment by foster999** [comment]
Could use yield to generate gptheme

**Comment by rowanhemsi** [comment]
As of v0.2.0, default theme used from pickle, to encourage users to explicitly pass a modified theme, rather than rewrite the default
